name: Main Workflow
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: npm
      - run: npm install
      - run: npm run compile
      - run: npm run test
  deploy-goerli:
    needs: test
    runs-on: ubuntu-latest
    name: Goerli deployment
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: npm
      - run: npm install
      - run: npm run compile
      - run: npm run deploy:goerli
        env:
          GOERLI_NODE_URL: ${{ secrets.GOERLI_NODE_URL }}
          GOERLI_MNEMONIC: ${{ secrets.GOERLI_MNEMONIC }}
      - name: Commit deployment
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Goerli deployment updated'
          add: 'deployments'

  # release:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   name: Release
  #   steps:
      # - uses: actions/checkout@v2
      # - name: Setup node
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: '16.x'
      #     cache: npm
      # - run: npm install
      # - run: npm run compile
  #     - run: npm run build
  #     - name: Semantic release
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  #       run: npx semantic-release
        