name: Main Workflow
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: npm
      - run: npm install
      - run: npm run compile
      - run: npm run test
  # release:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   name: Release
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Setup node
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: '16.x'
  #         cache: npm
  #     - run: npm install
  #     - run: npm run compile
  #     - run: npm run build
  #     - name: Semantic release
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  #       run: npx semantic-release
        